---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    component: scheduler
  name: custom-scheduler
spec:
  selector:
    matchLabels:
      component: scheduler
  replicas: 1
  template:
    metadata:
      labels:
        component: scheduler
    spec:
      priorityClassName: system-cluster-critical 
      serviceAccountName: custom-scheduler
      containers:
      - name: scheduler
        image: kschnitzer-custom-scheduler:development
        args:
        - --config=/etc/kubernetes/scheduler-config.yaml
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /healthz
            port: 10259
            scheme: HTTPS
          initialDelaySeconds: 15
        readinessProbe:
          httpGet:
            path: /healthz
            port: 10259
            scheme: HTTPS
        resources:
          requests:
            cpu: 1
            memory: 2Gi
          limits:
            cpu: 4
            memory: 2Gi
        securityContext:
          privileged: false
        volumeMounts:
        - name: scheduler-config
          mountPath: /etc/kubernetes
          readOnly: true
      hostNetwork: false
      hostPID: false
      volumes:
      - name: scheduler-config
        configMap:
          name: scheduler-config
