---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "kaschnit-scheduler.fullname" . }}-scheduler
  labels:
    {{- include "kaschnit-scheduler.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kaschnit-scheduler.fullname" . }}-scheduler
subjects:
- kind: ServiceAccount
  name: '{{ include "kaschnit-scheduler.serviceAccountName" . }}'
  namespace: '{{ .Release.Namespace }}'
