---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kaschnit-scheduler.fullname" . }}-config
data:
  scheduler-config.yaml: |
    ---
    apiVersion: kubescheduler.config.k8s.io/v1
    kind: KubeSchedulerConfiguration
    leaderElection:
      leaderElect: true
      resourceName: kaschnit-scheduler-scheduler
      resourceNamespace: {{ .Release.Namespace }}
      resourceLock: leases
    profiles:
    {{- range $profile := .Values.scheduler.profiles }}
    - schedulerName: {{ $profile.name | quote }}
      plugins: {{- toYaml $profile.plugins | nindent 8 }}
    {{- end }}
